[project]
name = "74-2025-12-google-live-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "google-genai>=1.55.0",
    "pyaudio>=0.2.14",
    "python-dotenv>=1.2.1",
]
